TRAIN_PATH="Animals"
CALLBACKS_PATH="CNN_basics_callbacks.pth.tar"
TENSORBOARD_WRITER_PATH="Tensorboard_Writer"
PREDICTION_PATH="Prediction"

BATCH_SIZE=128
LEARNING_RATE=0.001
EPOCH=13
CHANNEL_SIZE=3
RESHAPE_IMG_SIZE=128

TRAIN=False
LOAD=True
TEST_STEP=False
PREDICTION=True

    
    
    